function setup() {
  createCanvas(windowWidth, windowHeight);
  var x = 0;
  var y = 0;
  var w = width;
  var h = 20;
  fill(0);

  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);
  y = y + 40;
  rect(x, y, w, h);

}